import { PrismaClient } from "@prisma/client";
import LogHelper from "../helper/log.helper";

const prisma = new PrismaClient({
  log: [
    {
      emit: 'event',
      level: 'query',
    },
    {
      emit: 'stdout',
      level: 'error',
    },
    {
      emit: 'stdout',
      level: 'info',
    },
    {
      emit: 'stdout',
      level: 'warn',
    },
  ],
})


prisma.$on("query", (e) => {
  console.log('Query: ' + e.query)
  console.log('Params: ' + e.params)
  console.log('Duration: ' + e.duration + 'ms')
});

class BillCodeModel {
  id?: number;
  name: string;
  customer_id?: number | null;
  created_by: number;
  created_at: Date;
  payment_method_id: number;
  is_delete: boolean = false;
  is_confirm: boolean = true;
  confirmed_by: number;
  confirmed_at: Date;
  discount: number;
  delivery: number;
  date: Date;

  constructor(
    customer_id: number | null,
    created_by: number,
    payment_method_id: number,
    discount: number,
    delivery: number,
    date: Date,
    id: number | null = null
  ) {
    // Name will be uniquely generated by our model
    if (id != null) {
      this.id = id;
    }

    this.customer_id = customer_id;
    this.created_by = created_by;
    this.created_at = new Date();
    this.payment_method_id = payment_method_id;
    this.confirmed_at = this.created_at;
    this.confirmed_by = this.created_by;
    this.discount = discount;
    this.delivery = delivery;
    this.date = new Date(date);
    this.name = "";
  }

  async create() {
    const name = `INV-${this.date.getFullYear()}-${Math.floor(
      Math.random() * 10
    )}${Math.floor(Math.random() * 10)}${Math.floor(
      Math.random() * 10
    )}${Math.floor(Math.random() * 10)}${Math.floor(
      Math.random() * 10
    )}${Math.floor(Math.random() * 10)}${Math.floor(
      Math.random() * 10
    )}${Math.floor(Math.random() * 10)}`;

    return prisma.bill_code.create({
      data: {
        name: name,
        created_by: this.created_by,
        created_at: this.created_at,
        customer_id: this.customer_id,
        payment_method_id: this.payment_method_id,
        discount: this.discount,
        delivery: this.delivery,
        date: this.date,
      },
      select: {
        id: true,
        name: true,
        discount: true,
        delivery: true,
        payment_method: {
          select: {
            name: true,
            description: true,
            id: true,
          },
        },
        customer_id: true,
        user_bill_code_created_byTouser: {
          select: {
            id: true,
            name: true,
          },
        },
      },
    });
  }

  static countItemByReference(reference: string) {
    return prisma.bill.count({
      where: {
        item: {
          reference: reference,
        },
      },
    });
  }

  static countByCustomerId(customer_id: number) {
    return prisma.bill_code.count({
      where: {
        customer_id: customer_id,
        is_delete: false,
      },
    });
  }

  static countByCustomerIds(customer_ids: number[]) {
    return prisma.bill_code.groupBy({
      by: ["customer_id"],
      where: {
        customer_id: {
          in: customer_ids,
        },
        is_delete: false,
      },
      _count: true,
    });
  }

  countByDate(date: Date) {
    return prisma.bill_code.count({
      where: {
        date: {
          lte: new Date(date.getFullYear(), date.getMonth(), date.getDate(), 0, 0, 0, 0),
          gte: new Date(date.getFullYear(), date.getMonth() + 1, date.getDate(), 0, 0, 0, 0)
        },
      },
    });
  }

  static countByPaymentMethodIds(payment_method_ids: number[]) {
    return prisma.bill_code.groupBy({
      by: ["payment_method_id"],
      where: {
        payment_method_id: {
          in: payment_method_ids,
        },
        is_delete: false,
      },
      _count: true,
    });
  }

  static countByPaymentMethodId(payment_method_id: number) {
    return prisma.bill_code.count({
      where: {
        payment_method_id: payment_method_id,
        is_delete: false,
      },
    });
  }

  static fetchCodeById(id: number) {
    return prisma.bill.findUnique({
      where: {
        id: id
      },
      select: {
        bill_code: {
          select: {
            name: true,
            date: true,
            user_bill_code_created_byTouser: {
              select: {
                name: true
              }
            },
            customer: {
              select: {
                name: true,
                address: true,
                npwp: true,
                pic: true
              }
            },
            bill: {
              select: {
                item: {
                  select: {
                    reference: true,
                    description: true,
                    item_brand: {
                      select: {
                        name: true
                      }
                    }
                  }
                },
                quantity: true,
                id: true
              }
            }
          }
        }
      }
    })
  }

  static fetchArchive(
    year: number,
    month: number,
    offset: number,
    limit: number
  ) {
    const start_date = new Date(year, month - 1, 1, 0, 0, 0, 0);
    const end_date = new Date(year, month, 1, 0, 0, 0, 0);

    return prisma.bill_code.findMany({
      where: {
        AND: [
          {
            date: {
              gte: start_date,
            },
          },
          {
            date: {
              lt: end_date,
            },
          },
        ],
      },
      orderBy: {
        date: "asc",
      },
      take: limit,
      skip: offset,
      select: {
        name: true,
        id: true,
        customer: {
          select: {
            name: true,
          },
        },
        date: true,
        user_bill_code_created_byTouser: {
          select: {
            name: true
          }
        },
        created_at: true,
        is_delete: true,
        is_confirm: true,
      },
    });
  }

  static fetchArchiveYears() {
    return prisma.$queryRaw`SELECT DISTINCT(YEAR(bill_code.date)) AS year FROM bill_code ORDER BY bill_code.date ASC`;
  }

  static countArchiveByYear() {
    return prisma.$queryRaw`SELECT COUNT(bill_code.id) AS count, YEAR(bill_code.date) AS year FROM bill_code GROUP BY YEAR(bill_code.date)`;
  }

  static countArchiveByMonth(year: number) {
    return prisma.$queryRaw`SELECT COUNT(bill_code.id) AS count, MONTH(bill_code.date) AS month FROM bill_code WHERE YEAR(bill_code.date) = ${year} GROUP BY MONTH(bill_code.date)`;
  }

  static countArchive(year: number, month: number) {
    const start_date = new Date(year, month - 1, 1, 0, 0, 0, 0);
    const end_date = new Date(year, month, 1, 0, 0, 0, 0);

    return prisma.bill_code.count({
      where: {
        AND: [
          {
            date: {
              gte: start_date,
            },
          },
          {
            date: {
              lt: end_date,
            },
          },
        ],
      },
    });
  }
}

export default BillCodeModel;
