import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient()

class BillCodeModel {
  id?: number;
  name: string;
  customer_id?: number | null;
  created_by: number;
  created_at: Date;
  payment_method_id: number;
  is_delete: boolean = false;
  is_confirm: boolean = true;
  confirmed_by: number;
  confirmed_at: Date;
  discount: number;
  delivery: number;
  date: Date;

  constructor(
    customer_id: number | null,
    created_by: number,
    payment_method_id: number,
    discount: number,
    delivery: number,
    date: Date,
    id: number | null = null
  ) {
    // Name will be uniquely generated by our model
    if (id != null) {
      this.id = id;
    }

    this.customer_id = customer_id;
    this.created_by = created_by;
    this.created_at = new Date();
    this.payment_method_id = payment_method_id;
    this.confirmed_at = this.created_at;
    this.confirmed_by = this.created_by;
    this.discount = discount;
    this.delivery = delivery;
    this.date = new Date(date);
    this.name = "";
  }

  async create() {
    const name = `INV-${this.date.getFullYear()}-${Math.floor(
      Math.random() * 10
    )}${Math.floor(Math.random() * 10)}${Math.floor(
      Math.random() * 10
    )}${Math.floor(Math.random() * 10)}${Math.floor(
      Math.random() * 10
    )}${Math.floor(Math.random() * 10)}${Math.floor(
      Math.random() * 10
    )}${Math.floor(Math.random() * 10)}`;

    return prisma.bill_code.create({
      data: {
        name: name,
        created_by: this.created_by,
        created_at: this.created_at,
        customer_id: this.customer_id,
        payment_method_id: this.payment_method_id,
        discount: this.discount,
        delivery: this.delivery,
        date: this.date,
        is_confirm: this.is_confirm,
        confirmed_by: this.created_by,
        confirmed_at: this.created_at
      },
      select: {
        id: true,
        name: true,
        discount: true,
        delivery: true,
        payment_method: {
          select: {
            name: true,
            description: true,
            id: true,
          },
        },
        customer_id: true,
        user_bill_code_created_byTouser: {
          select: {
            id: true,
            name: true,
          },
        },
      },
    });
  }

  generateName(date: Date = new Date()) {
    return `INV-${date.getFullYear()}-${Math.floor(
      Math.random() * 10
    )}${Math.floor(Math.random() * 10)}${Math.floor(
      Math.random() * 10
    )}${Math.floor(Math.random() * 10)}${Math.floor(
      Math.random() * 10
    )}${Math.floor(Math.random() * 10)}${Math.floor(
      Math.random() * 10
    )}${Math.floor(Math.random() * 10)}`;
  }

  static countItemByReference(reference: string) {
    return prisma.bill.count({
      where: {
        item: {
          reference: reference,
        },
      },
    });
  }

  static countByCustomerId(customer_id: number) {
    return prisma.bill_code.count({
      where: {
        customer_id: customer_id,
        is_delete: false,
      },
    });
  }

  static countByCustomerIds(customer_ids: number[]) {
    return prisma.bill_code.groupBy({
      by: ["customer_id"],
      where: {
        customer_id: {
          in: customer_ids,
        },
        is_delete: false,
      },
      _count: true,
    });
  }

  countByDate(date: Date) {
    return prisma.bill_code.count({
      where: {
        date: {
          lte: new Date(date.getFullYear(), date.getMonth(), date.getDate(), 0, 0, 0, 0),
          gte: new Date(date.getFullYear(), date.getMonth() + 1, date.getDate(), 0, 0, 0, 0)
        },
      },
    });
  }

  static countByPaymentMethodIds(payment_method_ids: number[]) {
    return prisma.bill_code.groupBy({
      by: ["payment_method_id"],
      where: {
        payment_method_id: {
          in: payment_method_ids,
        },
        is_delete: false,
      },
      _count: true,
    });
  }

  static countByPaymentMethodId(payment_method_id: number) {
    return prisma.bill_code.count({
      where: {
        payment_method_id: payment_method_id,
        is_delete: false,
      },
    });
  }

  static fetchByDate(date: Date = new Date()) {
    return prisma.$queryRaw`
      SELECT (a.delivery + a.value - a.discount) AS value FROM (SELECT SUM((bill.price - bill.discount) * bill.quantity) AS value, bill_code.delivery, bill_code.discount
      FROM bill
      JOIN bill_code ON bill.bill_code_id = bill_code.id
      WHERE bill_code.is_confirm = 1
      AND bill_code.is_delete = 0
      AND YEAR(bill_code.date) = ${date.getFullYear()} AND MONTH(bill_code.date) = ${date.getMonth() + 1} AND DAY(bill_code.date) = ${date.getDate()}) AS a`;
  }

  static fetchMonthlyByDate(date: Date = new Date()){
    return prisma.$queryRaw`
      SELECT (a.delivery + a.value - a.discount) AS value FROM (SELECT SUM((bill.price - bill.discount) * bill.quantity) AS value, bill_code.delivery, bill_code.discount
      FROM bill
      JOIN bill_code ON bill.bill_code_id = bill_code.id
      WHERE bill_code.is_confirm = 1
      AND bill_code.is_delete = 0
      AND YEAR(bill_code.date) = ${date.getFullYear()} AND MONTH(bill_code.date) = ${date.getMonth() + 1}) AS a`;
  }

  static fetchCodeById(id: number) {
    return prisma.bill.findUnique({
      where: {
        id: id
      },
      select: {
        bill_code: {
          select: {
            name: true,
            date: true,
            user_bill_code_created_byTouser: {
              select: {
                name: true
              }
            },
            customer: {
              select: {
                name: true,
                address: true,
                npwp: true,
                pic: true
              }
            },
            bill: {
              select: {
                item: {
                  select: {
                    reference: true,
                    description: true,
                    item_brand: {
                      select: {
                        name: true
                      }
                    }
                  }
                },
                quantity: true,
                id: true
              }
            }
          }
        }
      }
    })
  }

  static fetchArchive(
    year: number,
    month: number,
    offset: number,
    limit: number
  ) {
    const start_date = new Date(year, month - 1, 1, 0, 0, 0, 0);
    const end_date = new Date(year, month, 1, 0, 0, 0, 0);

    return prisma.bill_code.findMany({
      where: {
        AND: [
          {
            date: {
              gte: start_date,
            },
          },
          {
            date: {
              lt: end_date,
            },
          },
        ],
      },
      orderBy: {
        date: "asc",
      },
      take: limit,
      skip: offset,
      select: {
        name: true,
        id: true,
        customer: {
          select: {
            name: true,
          },
        },
        date: true,
        user_bill_code_created_byTouser: {
          select: {
            name: true
          }
        },
        created_at: true,
        is_delete: true,
        is_confirm: true,
      },
    });
  }

  static fetchArchiveYears() {
    return prisma.$queryRaw`SELECT DISTINCT(YEAR(bill_code.date)) AS year FROM bill_code ORDER BY bill_code.date ASC`;
  }

  static countArchiveByYear() {
    return prisma.$queryRaw`SELECT COUNT(bill_code.id) AS count, YEAR(bill_code.date) AS year FROM bill_code GROUP BY YEAR(bill_code.date)`;
  }

  static countArchiveByMonth(year: number) {
    return prisma.$queryRaw`SELECT COUNT(bill_code.id) AS count, MONTH(bill_code.date) AS month FROM bill_code WHERE YEAR(bill_code.date) = ${year} GROUP BY MONTH(bill_code.date)`;
  }

  static countArchive(year: number, month: number) {
    const start_date = new Date(year, month - 1, 1, 0, 0, 0, 0);
    const end_date = new Date(year, month, 1, 0, 0, 0, 0);

    return prisma.bill_code.count({
      where: {
        AND: [
          {
            date: {
              gte: start_date,
            },
          },
          {
            date: {
              lt: end_date,
            },
          },
        ],
      },
    });
  }

  static fetchChartItems(monthly: boolean, limit: number, offset: number) {
    const date = new Date();
    const start_date = new Date();

    if (monthly) {
      date.setMonth(date.getMonth() - offset);
      start_date.setMonth(date.getMonth() - limit - offset);

      const prev_date = new Date();
      const start_prev_date = new Date();
      prev_date.setMonth(date.getMonth() - offset - 12);
      start_prev_date.setMonth(date.getMonth() - limit - offset - 12);
      
      return prisma.$transaction([
        prisma.$queryRawUnsafe(`SELECT year, month, (delivery + value - discount) AS value, diff FROM (
          SELECT YEAR(bill_code.date) AS year, MONTH(bill_code.date) AS month, SUM(bill_code.delivery) AS delivery, SUM(bill_code.discount) AS discount, SUM(a.value) AS value, TIMESTAMPDIFF(MONTH, LAST_DAY(curdate()), STR_TO_DATE(CONCAT(YEAR(bill_code.date),'-',LPAD(MONTH(bill_code.date),2,'00'),'-',LPAD(DAY(LAST_DAY(bill_code.date)),2,'00')), '%Y-%m-%d')) AS diff
          FROM bill_code
          JOIN (
            SELECT (SUM(bill.price - bill.discount) * bill.quantity) AS value, bill_code_id
            FROM bill
            GROUP BY bill.bill_code_id
          ) AS a
          ON bill_code.id = a.bill_code_id
          WHERE bill_code.date BETWEEN '${start_date.getFullYear().toString()}-${(start_date.getMonth() + 1).toString().padStart(2, "0")}-01' AND LAST_DAY('${date.getFullYear().toString()}-${(date.getMonth() + 1).toString().padStart(2, "0")}-01')
          AND bill_code.is_confirm = 1
          AND bill_code.is_delete = 0
          GROUP BY YEAR(bill_code.date), MONTH(bill_code.date)) AS bill_a`),
        prisma.$queryRawUnsafe(`SELECT year, month, (delivery + value - discount) AS value, diff FROM (
          SELECT YEAR(bill_code.date) AS year, MONTH(bill_code.date) AS month, SUM(bill_code.delivery) AS delivery, SUM(bill_code.discount) AS discount, SUM(a.value) AS value, TIMESTAMPDIFF(MONTH, LAST_DAY(curdate()), STR_TO_DATE(CONCAT(YEAR(bill_code.date),'-',LPAD(MONTH(bill_code.date),2,'00'),'-',LPAD(DAY(LAST_DAY(bill_code.date)),2,'00')), '%Y-%m-%d')) AS diff
          FROM bill_code
          JOIN (
            SELECT (SUM(bill.price - bill.discount) * bill.quantity) AS value, bill_code_id
            FROM bill
            GROUP BY bill.bill_code_id
            ) AS a
          ON bill_code.id = a.bill_code_id
          WHERE bill_code.date BETWEEN '${start_prev_date.getFullYear().toString()}-${(start_prev_date.getMonth() + 1).toString().padStart(2, "0")}-01' AND LAST_DAY('${prev_date.getFullYear().toString()}-${(prev_date.getMonth() + 1).toString().padStart(2, "0")}-01')
          AND bill_code.is_confirm = 1
          AND bill_code.is_delete = 0
          GROUP BY YEAR(bill_code.date), MONTH(bill_code.date)) AS bill_a`),
      ])
    } else {
      date.setDate(date.getDate() - offset);
      start_date.setDate(date.getDate() - limit - offset);
      return prisma.$queryRawUnsafe(`SELECT diff, (delivery + value - discount) AS value FROM (
        SELECT datediff(curdate(), STR_TO_DATE(CONCAT(YEAR(bill_code.date),'-',LPAD(MONTH(bill_code.date),2,'00'),'-',LPAD(DAY(bill_code.date),2,'00')), '%Y-%m-%d')) AS diff, SUM(a.value) AS value, SUM(delivery) AS delivery, SUM(discount) AS discount
        FROM bill_code
        JOIN (
          SELECT (SUM(bill.price - bill.discount) * bill.quantity) AS value, bill_code_id
          FROM bill
          GROUP BY bill.bill_code_id
        ) AS a
        ON bill_code.id = a.bill_code_id
        WHERE bill_code.date BETWEEN '${start_date.getFullYear().toString()}-${(start_date.getMonth() + 1).toString().padStart(2, "0")}-${(start_date.getDate()).toString().padStart(2, "0")}' AND '${date.getFullYear().toString()}-${(date.getMonth() + 1).toString().padStart(2, "0")}-${(date.getDate()).toString().padStart(2, "0")}'
        AND bill_code.is_confirm = 1
        AND bill_code.is_delete = 0
        GROUP BY YEAR(bill_code.date), MONTH(bill_code.date), DAY(bill_code.date)) AS bill_a`);
    }

  };

  static fetchByCustomerId(customer_id: number | null){
    if(customer_id == null){
      return prisma.$queryRaw`
        SELECT SUM(bill_.value + bill_code.delivery - bill_code.discount) AS value, COUNT(bill_code) AS count
        FROM bill_code
        JOIN (
          SELECT SUM(bill.quantity * (bill.price - bill.discount)) AS value, bill.bill_code_id
          FROM bill
          GROUP BY bill.bill_code_id
        ) AS bill_
        ON bill_code.id = bill_.bill_code_id = bill_code.id
        WHERE bill_code.customer_id IS NULL
      `
    } else {
      return prisma.$queryRaw`
        SELECT SUM(bill_.value + bill_code.delivery - bill_code.discount) AS value, COUNT(bill_code) AS count
        FROM bill_code
        JOIN (
          SELECT SUM(bill.quantity * (bill.price - bill.discount)) AS value, bill.bill_code_id
          FROM bill
          GROUP BY bill.bill_code_id
        ) AS bill_
        ON bill_code.id = bill_.bill_code_id = bill_code.id
        WHERE bill_code.customer_id = ${customer_id}
      `
    }
    
  }
}

export default BillCodeModel;
