import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

class BillCodeModel {
  id?: number;
  name: string;
  customer_id?: number | null;
  created_by: number;
  created_at: Date;
  payment_method_id: number;
  is_delete: boolean = false;
  is_confirm: boolean = true;
  confirmed_by: number;
  confirmed_at: Date;
  discount: number;
  delivery: number;
  date: Date | null;

  constructor(
    customer_id: number | null,
    created_by: number,
    payment_method_id: number,
    discount: number,
    delivery: number,
    date: Date | null = null,
    id: number | null = null
  ) {
    // Name will be uniquely generated by our model
    if (id != null) {
      this.id = id;
    }

    this.customer_id = customer_id;
    this.created_by = created_by;
    this.created_at = new Date();
    this.payment_method_id = payment_method_id;
    this.confirmed_at = this.created_at;
    this.confirmed_by = this.created_by;
    this.discount = discount;
    this.delivery = delivery;
    this.date = date;
    this.name = this.generateName(this.created_at);
  }

  create() {
    return prisma.bill_code.create({
      data: {
        name: this.name,
        created_by: this.created_by,
        created_at: this.created_at,
        customer_id: this.customer_id,
        payment_method_id: this.payment_method_id,
        discount: this.discount,
        delivery: this.delivery,
        date: this.date,
        is_confirm: this.is_confirm,
        confirmed_by: this.created_by,
        confirmed_at: this.created_at
      },
      select: {
        id: true,
        name: true,
        discount: true,
        delivery: true,
        payment_method: {
          select: {
            name: true,
            description: true,
            id: true,
          },
        },
        customer_id: true,
        user_bill_code_created_byTouser: {
          select: {
            id: true,
            name: true,
          },
        },
      },
    });
  }

  generateName(date: Date = new Date()) {
    return `INV-${date.getFullYear()}-${Math.floor(
      Math.random() * 10
    )}${Math.floor(Math.random() * 10)}${Math.floor(
      Math.random() * 10
    )}${Math.floor(Math.random() * 10)}${Math.floor(
      Math.random() * 10
    )}${Math.floor(Math.random() * 10)}${Math.floor(
      Math.random() * 10
    )}${Math.floor(Math.random() * 10)}`;
  }

  static countItemByReference(reference: string) {
    return prisma.bill.count({
      where: {
        item: {
          reference: reference,
        },
      },
    });
  }

  static countByCustomerId(customer_id: number) {
    return prisma.bill_code.count({
      where: {
        customer_id: customer_id,
        is_delete: false,
      },
    });
  }

  static countByCustomerIds(customer_ids: number[]) {
    return prisma.bill_code.groupBy({
      by: ["customer_id"],
      where: {
        customer_id: {
          in: customer_ids,
        },
        is_delete: false,
      },
      _count: true,
    });
  }

  countByDate(date: Date) {
    // Time is already adjusted to 00:00:00.00
    const start_date = date;
    const end_date = date;
    end_date.setDate(end_date.getDate() + 1);
    return prisma.bill_code.count({
      where: {
        AND: [
          {
            created_at: {
              lt: end_date,
            },
          },
          {
            created_at: {
              gte: start_date,
            },
          },
        ],
      },
    });
  }

  static countByPaymentMethodIds(payment_method_ids: number[]) {
    return prisma.bill_code.groupBy({
      by: ["payment_method_id"],
      where: {
        payment_method_id: {
          in: payment_method_ids,
        },
        is_delete: false,
      },
      _count: true,
    });
  }

  static countByPaymentMethodId(payment_method_id: number) {
    return prisma.bill_code.count({
      where: {
        payment_method_id: payment_method_id,
        is_delete: false,
      },
    });
  }

  static fetchByDate(date: Date = new Date()){
    return prisma.$queryRaw`SELECT (a.delivery + a.value - a.discount) AS value FROM (SELECT SUM((bill.price - bill.discount) * bill.quantity) AS value, bill_code.delivery, bill_code.discount
    FROM bill
    JOIN bill_code ON bill.bill_code_id = bill_code.id
    WHERE bill_code.is_confirm = 1
    AND bill_code.is_delete = 0
    AND YEAR(bill_code.date) = ${date.getFullYear()} AND MONTH(bill_code.date) = ${date.getMonth() + 1} AND DAY(bill_code.date) = ${date.getDate()}) a`;
  }
}

export default BillCodeModel;
