/**
 * Katalog pesan galat, kini berisi key i18n dan bukan lagi kalimat berbahasa
 * Indonesia.
 *
 * KUNCI enum sengaja dipertahankan apa adanya, termasuk yang salah eja seperti
 * "Sales invoice creation faled" dan "Good receipt requried". Kunci itu dipakai
 * di 747 tempat pada 53 berkas; mengubahnya berarti menyentuh semuanya tanpa
 * manfaat apa pun, karena yang dikirim ke klien adalah NILAI-nya.
 *
 * Terjemahan bahasa Indonesia yang dulu ada di sini dipindahkan ke
 * docs/i18n/id.json supaya bisa langsung dipakai berkas terjemahan frontend.
 *
 * PENTING: balasan galat dikirim sebagai string mentah, bukan JSON
 * (utils/validate.helper.ts dan utils/error.helper.ts). Frontend menampilkan
 * isinya apa adanya, jadi rilis backend ini HARUS berbarengan dengan frontend
 * yang sudah bisa menerjemahkan key. Kalau tidak, pengguna akan melihat
 * tulisan seperti "validation.name.required" di layar.
 */
enum ErrorList {
  "Auth error" = "error.auth",
  "Not found" = "error.notFound",
  "Unknown error" = "error.unknown",
  "Parameter error" = "error.parameter",
  "Delete error" = "error.delete",
  "Duplicate error" = "error.duplicate",
  "Internal server error" = "error.internalServer",
  "Unable to delete" = "error.unableToDelete",
  "No changes" = "error.noChanges",

  "ID is required" = "validation.id.required",
  "ID must be numeric" = "validation.id.numeric",
  "ID must be integer" = "validation.id.integer",
  "UUID required" = "validation.uuid.required",
  "Name required" = "validation.name.required",
  "Address required" = "validation.address.required",
  "Date required" = "validation.date.required",
  "Quantity required" = "validation.quantity.required",
  "Quantity is required" = "validation.quantity.required",
  "Quantity must be numeric" = "validation.quantity.numeric",
  "Price required" = "validation.price.required",
  "Price is required" = "validation.price.required",
  "Price must be numeric" = "validation.price.numeric",
  "Discount required" = "validation.discount.required",
  "Discount must be numeric" = "validation.discount.numeric",
  "Discount > price" = "validation.discount.greaterThanPrice",
  "Amount is required" = "validation.amount.required",
  "Amount must be numeric" = "validation.amount.numeric",
  "Keyword is required" = "validation.keyword.required",
  "Item is required" = "validation.item.required",
  "Item ID required" = "validation.item.idRequired",
  "Item ID must be numeric" = "validation.item.idNumeric",

  "Day is required" = "validation.day.required",
  "Day must be numeric" = "validation.day.numeric",
  "Month is required" = "validation.month.required",
  "Month must be numeric" = "validation.month.numeric",
  "Year is required" = "validation.year.required",
  "Year must be numeric" = "validation.year.numeric",

  "Page is required" = "validation.page.required",
  "Page must be numeric" = "validation.page.numeric",
  "Page size is required" = "validation.pageSize.required",
  "Page size must be numeric" = "validation.pageSize.numeric",
  "Sort by required" = "validation.sortBy.required",
  "Sort direction only supports ascending or descending" = "validation.sortDirection.invalid",
  "Archives parameter error" = "validation.archives.parameter",

  "Supplier name too long" = "validation.supplier.nameTooLong",
  "Supplier NPWP too long" = "validation.supplier.npwpTooLong",
  "Customer name too long" = "validation.customer.nameTooLong",
  "Customer PIC too long" = "validation.customer.picTooLong",
  "Customer address too long" = "validation.customer.addressTooLong",
  "Company name too long" = "validation.company.nameTooLong",
  "Payment method name too long" = "validation.paymentMethod.nameTooLong",
  "Brand name too long" = "validation.brand.nameTooLong",
  "Product type name too long" = "validation.productType.nameTooLong",
  "Expense type name too long" = "validation.expenseType.nameTooLong",
  "Product reference too long" = "validation.product.referenceTooLong",
  "Product description too long" = "validation.product.descriptionTooLong",

  "User not active" = "user.notActive",
  "User not found" = "user.notFound",
  "User already exist" = "user.alreadyExists",
  "Role not found" = "user.roleNotFound",
  "Password is required" = "validation.password.required",
  "User role required" = "validation.userRole.required",
  "Username is required" = "validation.username.required",

  "Package item id required" = "validation.package.itemIdRequired",
  "Package item unit id required" = "validation.package.itemUnitIdRequired",
  "Package item quantity required" = "validation.package.itemQuantityRequired",
  "Package item price required" = "validation.package.itemPriceRequired",
  "Package item discount required" = "validation.package.itemDiscountRequired",
  "Package ID is required" = "validation.package.idRequired",
  "Package ID must be numeric" = "validation.package.idNumeric",
  "Package name required" = "validation.package.nameRequired",
  "Package description required" = "validation.package.descriptionRequired",
  "Package items required" = "validation.package.itemsRequired",

  "Product not found" = "product.notFound",
  "Product unit not found" = "product.unitNotFound",
  "Product package not found" = "product.packageNotFound",
  "Product cannot be deleted" = "product.cannotBeDeleted",
  "Product reference is required" = "validation.product.referenceRequired",
  "Product description is required" = "validation.product.descriptionRequired",
  "Product brand is required" = "validation.product.brandRequired",
  "Product type is required" = "validation.product.typeRequired",
  "Product unit is required" = "validation.product.unitRequired",
  "Product minimum stock is required" = "validation.product.minimumStockRequired",
  "Product ID is required" = "validation.product.idRequired",
  "Product unit ID is required" = "validation.product.unitIdRequired",
  "Product ID must be numeric" = "validation.product.idNumeric",
  "Product unit must be an array" = "validation.product.unitArray",
  "Reference unique constraint" = "product.referenceDuplicate",

  "Brand unique constraint" = "brand.duplicate",
  "Brand is required" = "validation.brand.required",
  "Brand must be an array" = "validation.brand.array",
  "Brand must be an integer" = "validation.brand.integer",
  "Type not found" = "type.notFound",
  "Type is required" = "validation.type.required",
  "Type must be an array" = "validation.type.array",
  "Type must be an integer" = "validation.type.integer",

  "Salesman already exists" = "salesman.alreadyExists",
  "Salesman not found" = "salesman.notFound",
  "Salesman name required" = "validation.salesman.nameRequired",

  "Customer not found" = "customer.notFound",
  "Customer name is required" = "validation.customer.nameRequired",
  "Customer PIC is required" = "validation.customer.picRequired",
  "Customer phone number is required" = "validation.customer.phoneRequired",
  "Customer address is required" = "validation.customer.addressRequired",
  "Customer NPWP is required" = "validation.customer.npwpRequired",
  "Customer ID is required" = "validation.customer.idRequired",
  "CUstomer ID must be integer" = "validation.customer.idInteger",

  "Supplier has been used" = "supplier.hasBeenUsed",
  "Supplier ID required" = "validation.supplier.idRequired",
  "Supplier ID is required" = "validation.supplier.idRequired",
  "Supplier ID must be numeric" = "validation.supplier.idNumeric",
  "Company ID required" = "validation.company.idRequired",

  "Invoice already confirmed" = "invoice.alreadyConfirmed",
  "Invoice already deleted" = "invoice.alreadyDeleted",
  "Invoice not found" = "invoice.notFound",
  "Invoice name required" = "validation.invoice.nameRequired",
  "Bill exists" = "invoice.billExists",
  "Tax invoice required" = "validation.invoice.taxRequired",

  "Purchase invoice not found" = "purchaseInvoice.notFound",
  "Purchase invoice already confirmed" = "purchaseInvoice.alreadyConfirmed",
  "Purchase invoice already deleted" = "purchaseInvoice.alreadyDeleted",
  "Purchase invoice name required" = "validation.purchaseInvoice.nameRequired",

  "Payment method required" = "validation.paymentMethod.required",
  "Payment method must be numeric" = "validation.paymentMethod.numeric",
  "Payment status required" = "validation.paymentStatus.required",
  "Payment status is required" = "validation.paymentStatus.required",
  "Payment is required" = "validation.payment.required",
  "Payment must be an array" = "validation.payment.array",
  "Payment date is required" = "validation.payment.dateRequired",
  "Delivery required" = "validation.delivery.required",
  "Delivery must be numeric" = "validation.delivery.numeric",
  "Service required" = "validation.service.required",
  "Service must be numeric" = "validation.service.numeric",

  "Good receipt not found" = "goodReceipt.notFound",
  "Good receipt already confirmed" = "goodReceipt.alreadyConfirmed",
  "Good receipt already deleted" = "goodReceipt.alreadyDeleted",
  "Good receipt not confirmed" = "goodReceipt.notConfirmed",
  "Good receipt creation failed" = "goodReceipt.creationFailed",
  "Good receipt requried" = "validation.goodReceipt.required",
  "Good receipt required" = "validation.goodReceipt.required",
  "Good receipt ID required" = "validation.goodReceipt.idRequired",
  "Good receipt must be array" = "validation.goodReceipt.array",

  "Sales invoice creation faled" = "salesInvoice.documentCreationFailed",
  "Sales invoice creation failed" = "salesInvoice.creationFailed",
  "Sales invoice not found" = "salesInvoice.notFound",
  "Sales invoice item must be an array" = "validation.salesInvoice.itemArray",
  "Sales invoice ID is required" = "validation.salesInvoice.idRequired",
  "Sales invoice ID must be numeric" = "validation.salesInvoice.idNumeric",
  "Sales invoice payment is greater than value" = "salesInvoice.paymentExceedsValue",
  "Sales invoice payment not found" = "salesInvoice.paymentNotFound",
  "Receivable exceed sales invoice" = "receivable.exceedsSalesInvoice",

  "Sales return exists" = "salesReturn.alreadyExists",
  "Sales return already deleted" = "salesReturn.alreadyDeleted",
  "Sales return creation failed" = "salesReturn.creationFailed",
  "Sales return insufficient" = "salesReturn.exceedsPurchased",
  "Sales return items required" = "validation.salesReturn.itemsRequired",
  "Delete bill sales return constraint" = "salesReturn.blocksInvoiceDeletion",

  "Sales deposit creation failed" = "salesDeposit.creationFailed",
  "Sales deposit not found" = "salesDeposit.notFound",
  "Sales deposit payment is greater than value" = "salesDeposit.paymentExceedsValue",
  "Deposit already confirmed" = "salesDeposit.alreadyConfirmed",

  "Adjustment case not found" = "adjustmentCase.notFound",
  "Adjustment case has not been confirmed" = "adjustmentCase.notConfirmed",
  "Adjustment case has been confirmed" = "adjustmentCase.alreadyConfirmed",
  "Adjustment case has been deleted" = "adjustmentCase.alreadyDeleted",
  "Adjustment case type is required" = "validation.adjustmentCase.typeRequired",
  "Adjustment case company ID is required" = "validation.adjustmentCase.companyIdRequired",
  "Adjustment case lost type must be boolean" = "validation.adjustmentCase.lostTypeBoolean",
  "Adjustment case found type must be boolean" = "validation.adjustmentCase.foundTypeBoolean",

  "Expense not found" = "expense.notFound",
  "Expense type not found" = "expenseType.notFound",
  "Expense type has child" = "expenseType.hasChild",
  "Expense type name is required" = "validation.expenseType.nameRequired",
  "Expense type description is required" = "validation.expenseType.descriptionRequired",

  "Promotion not found" = "promotion.notFound",
  "Promotion name required" = "validation.promotion.nameRequired",
  "Promotion description required" = "validation.promotion.descriptionRequired",
  "Promotion start date required" = "validation.promotion.startDateRequired",
  "Promotion end date required" = "validation.promotion.endDateRequired",
  "Promotion target required" = "validation.promotion.targetRequired",
  "Promotion target must be numeric" = "validation.promotion.targetNumeric",
  "Promotion brand is required" = "validation.promotion.brandRequired",
  "Promotion brand must be an array" = "validation.promotion.brandArray",

  "Invalid status update" = "status.invalidUpdate",
  "Invalid group report" = "report.invalidGroup",
  "View by mutation required" = "validation.viewByMutation.required",
  "View by mutation must be either document date or creation date" = "validation.viewByMutation.invalid",

  "Return date is required" = "validation.return.dateRequired",
  "Return name is required" = "validation.return.nameRequired",
  "Return payment method is required" = "validation.return.paymentMethodRequired",
  "Return payment method must be either Cash or Transfer" = "validation.return.paymentMethodInvalid",
  "Return payment name is required" = "validation.return.paymentNameRequired",
  "Return payment bank is required" = "validation.return.paymentBankRequired",
  "Return payment number is required" = "validation.return.paymentNumberRequired",
}

export default ErrorList;
