enum ErrorList {
  "Auth error" = "Terjadi kesalahan pada saat melakukan autentikasi. Mohon periksa kembali informasi login anda.",
  "Not found" = "Data tidak ditemukan.",
  "Unknown error" = "Terjadi kesalahan yang tidak diketahui. Mohon hubungi administrator.",
  "Parameter error" = "Terjadi kesalahan pada parameter yang diberikan. Mohon periksa kembali.",
  "Delete error" = "Terjadi kesalahan pada saat menghapus data. Mohon hubungi administrator.",
  "Duplicate error" = "Data yang anda masukkan sudah ada sebelumnya. Mohon periksa kembali.",
  "ID is required" = "ID tidak boleh kosong.",
  "ID must be numeric" = "ID harus berupa angka.",
  "Address required" = "Alamat tidak boleh kosong.",
  "User not active" = "Pengguna tidak aktif.",
  "User not found" = "Pengguna tidak ditemukan.",
  "User already exist" = "Pengguna sudah ada sebelumnya.",
  "Role not found" = "Peran tidak ditemukan.",
  "UUID required" = "UUID tidak boleh kosong.",
  "Package item id required" = "ID item paket tidak boleh kosong.",
  "Package item unit id required" = "ID satuan item paket tidak boleh kosong.",
  "Package item quantity required" = "Kuantitas item paket tidak boleh kosong.",
  "Package item price required" = "Harga item paket tidak boleh kosong.",
  "Package item discount required" = "Diskon item paket tidak boleh kosong.",
  "Package ID is required" = "ID paket tidak boleh kosong.",
  "Package ID must be numeric" = "ID paket harus berupa angka.",
  "Sales return items required" = "Item retur penjualan tidak boleh kosong.",
  "Sales invoice creation faled" = "Gagal membentuk dokumen penjualan.",
  "Item ID required" = "ID item tidak boleh kosong.",
  "Item ID must be numeric" = "ID item harus berupa angka.",
  "Price required" = "Harga tidak boleh kosong.",
  "Price must be numeric" = "Harga harus berupa angka.",
  "Discount required" = "Diskon tidak boleh kosong.",
  "Discount must be numeric" = "Diskon harus berupa angka.",
  "Invalid status update" = "Tidak dapat memperbarui status. Status yang diberikan tidak valid.",

  "Salesman already exists" = "Sales sudah ada sebelumnya.",

  "Salesman not found" = "Sales tidak ditemukan.",
  "Salesman name required" = "Nama sales tidak boleh kosong.",

  "Product not found" = "Data produk tidak ditemukan.",
  "Product unit not found" = "Data satuan produk tidak ditemukan.",
  "Product package not found" = "Data paket produk tidak ditemukan.",
  "Product reference is required" = "Referensi produk tidak boleh kosong.",
  "Product description is required" = "Deskripsi produk tidak boleh kosong.",
  "Product brand is required" = "Merek produk tidak boleh kosong.",
  "Product type is required" = "Tipe produk tidak boleh kosong.",
  "Product unit is required" = "Satuan produk tidak boleh kosong.",
  "Product minimum stock is required" = "Stok minimum produk tidak boleh kosong.",
  "Product ID is required" = "ID produk tidak boleh kosong.",
  "Product unit ID is required" = "ID satuan produk tidak boleh kosong.",
  "Product ID must be numeric" = "ID produk harus berupa angka.",
  "Product cannot be deleted" = "Produk tidak dapat dihapus karena sudah digunakan dalam transaksi.",
  "Quantity required" = "Kuantitas tidak boleh kosong.",
  "Price is required" = "Harga tidak boleh kosong.",
  "Package name required" = "Nama paket tidak boleh kosong.",
  "Package description required" = "Deskripsi paket tidak boleh kosong.",
  "Package items required" = "Item paket tidak boleh kosong.",
  "Brand unique constraint" = "Nama merek sudah ada sebelumnya.",
  "Reference unique constraint" = "Referensi sudah ada sebelumnya.",

  "Unable to delete" = "Tidak dapat menghapus data.",
  "Invoice already confirmed" = "Invoice sudah dikonfirmasi.",
  "Invoice already deleted" = "Invoice sudah dihapus.",
  "Invoice not found" = "Data invoice tidak ditemukan.",
  "Purchase invoice not found" = "Data invoice pembelian tidak ditemukan.",
  "Purchase invoice already confirmed" = "Invoice pembelian sudah dikonfirmasi.",
  "Purchase invoice already deleted" = "Invoice pembelian sudah dihapus.",
  "Payment method required" = "Metode pembayaran tidak boleh kosong.",
  "Payment method must be numeric" = "Metode pembayaran harus berupa angka.",
  "Payment status is required" = "Status pembyaaran tidak boleh kosong.",
  "Delivery required" = "Pengiriman tidak boleh kosong.",
  "Service required" = "Biaya layanan tidak boleh kosong.",

  "Good receipt not found" = "Data penerimaan barang tidak ditemukan.",
  "Good receipt already confirmed" = "Penerimaan barang sudah dikonfirmasi.",
  "Good receipt already deleted" = "Penerimaan barang sudah dihapus.",
  "Good receipt not confirmed" = "Penerimaan barang belum dikonfirmasi.",
  "Good receipt requried" = "Penerimaan barang tidak boleh kosong.",

  "Date required" = "Tanggal tidak boleh kosong.",
  "Return date is required" = "Tanggal pengembalian tidak boleh kosong",
  "Return payment method must be either Cash or Transfer" = "Metode pengembalian kelebihan pembayaran harus berupa Cash atau Transfer bank",
  "Return name is required" = "Nama penerima kelebihan dana tidak boleh kosong",
  "Return payment bank is required" = "Nama bank untuk pengembalian kelebihan dana tidak boleh kosong",
  "Return payment number is required" = "Nomor akun bank untuk pengembalian kelebihan dana tidak boleh kosong",

  "Name required" = "Nama tidak boleh kosong.",
  "Supplier ID required" = "ID supplier tidak boleh kosong.",
  "Company ID required" = "ID perusahaan tidak boleh kosong.",
  "Purchase invoice name required" = "Nama invoice pembelian tidak boleh kosong.",
  "Adjustment case not found" = "Data kasus penyesuaian tidak ditemukan.",
  "Adjustment case has not been confirmed" = "Data kasus penyesuaian belum dikonfirmasi",
  "Adjustment case type is required" = "Tipe kasus penyesuaian tidak boleh kosong.",
  "Adjustment case company ID is required" = "ID perusahaan kasus penyesuaian tidak boleh kosong.",
  "Adjustment case lost type must be boolean" = "Tipe kasus penyesuaian hilang harus berupa boolean.",
  "Adjustment case found type must be boolean" = "Tipe kasus penyesuaian ditemukan harus berupa boolean.",
  "Delete bill sales return constraint" = "Tidak dapat menghapus faktur karena ada retur penjualan yang terkait.",
  "Adjustment case has been confirmed" = "Data kasus penyesuaian sudah dikonfirmasi",
  "Adjustment case has been deleted" = "Data kasus penyesuaian sudah dihapus",

  "Expense type not found" = "Data jenis pengeluaran tidak ditemukan.",
  "Expense type has child" = "Jenis pengeluaran memiliki sub jenis.",

  "No changes" = "Tidak ada perubahan.",

  "Password is required" = "Password tidak boleh kosong.",
  "User role required" = "Role pengguna tidak boleh kosong.",
  "Username is required" = "Username tidak boleh kosong.",

  "Item is required" = "Item tidak boleh kosong.",
  "Discount > price" = "Diskon tidak boleh lebih besar dari harga.",
  "Internal server error" = "Terjadi kesalahan pada server. Mohon hubungi administrator.",
  "Bill exists" = "Faktur sudah ada sebelumnya.",
  "Type not found" = "Tipe tidak ditemukan.",

  "Customer name is required" = "Nama pelanggan tidak boleh kosong.",
  "Customer PIC is required" = "PIC pelanggan tidak boleh kosong.",
  "Customer phone number is required" = "Nomor telepon pelanggan tidak boleh kosong.",
  "Customer address is required" = "Alamat pelanggan tidak boleh kosong.",
  "Customer NPWP is required" = "NPWP pelanggan tidak boleh kosong.",
  "Customer not found" = "Pelanggan tidak ditemukan.",
  "Customer ID is required" = "ID pelanggan tidak boleh kosong.",
  "CUstomer ID must be integer" = "Kesalahan pada ID pelanggan.",

  "Sales return exists" = "Retur penjualan sudah ada sebelumnya.",
  "Sales return already deleted" = "Data retur penjualan sudah dihapus.",
  "ID must be integer" = "Kesalahan pada ID yang diberikan.",
  "Expense type name is required" = "Nama jenis pengeluaran tidak boleh kosong.",
  "Expense type description is required" = "Deskripsi jenis pengeluaran tidak boleh kosong.",

  "Day is required" = "Tanggal tidak boleh kosong",
  "Day must be numeric" = "Tanggal harus berupa angka",
  "Month is required" = "Bulan tidak boleh kosong.",
  "Month must be numeric" = "Bulan harus berupa angka.",
  "Year is required" = "Tahun tidak boleh kosong.",
  "Year must be numeric" = "Tahun harus berupa angka.",

  "Promotion name required" = "Nama promosi tidak boleh kosong.",
  "Promotion description required" = "Deskripsi promosi tidak boleh kosong.",
  "Promotion start date required" = "Tanggal mulai promosi tidak boleh kosong.",
  "Promotion end date required" = "Tanggal akhir promosi tidak boleh kosong.",
  "Promotion target required" = "Target promosi tidak boleh kosong.",
  "Promotion target must be numeric" = "Target promosi harus berupa angka.",
  "Supplier ID is required" = "ID supplier tidak boleh kosong.",
  "Supplier ID must be numeric" = "ID supplier harus berupa angka.",
  "Promotion brand is required" = "Merek promosi tidak boleh kosong.",
  "Promotion brand must be an array" = "Merek promosi harus berupa array.",
  "Product unit must be an array" = "Satuan barang harus berupa array.",

  "Sales invoice creation failed" = "Gagal membentuk nota baru.",
  "Good receipt creation failed" = "Gagal membentuk penerimaan barang baru.",
  "Sales deposit creation failed" = "Gagal membentuk deposit baru.",
  "Sales return creation failed" = "Gagal membentuk retur penjualan baru.",

  "Archives parameter error" = "Terjadi kesalahan pada parameter arsip.",
  "Sales invoice item must be an array" = "Pencarian harus berupa array.",
  "Quantity is required" = "Kuantitas tidak boleh kosong.",
  "Quantity must be numeric" = "Kuantitas harus berupa angka.",
  "Sales invoice ID is required" = "Data barang tidak boleh kosong.",
  "Sales invoice ID must be numeric" = "Data barang harus berupa angka",

  "Sales return insufficient" = "Retur lebih besar daripada barang yang dibeli.",
  "Invoice name required" = "Nama faktur tidak boleh kosong",
  "Tax invoice required" = "Faktur pajak tidak boleh kosong",
  "Good receipt ID required" = "ID penerimaan barang tidak boleh kosong",
  "Good receipt required" = "Penerimaan barang tidak boleh kosong",
  "Good receipt must be array" = "Penerimaan barang harus berupa array",

  "Brand is required" = "Merek tidak boleh kosong",
  "Brand must be an array" = "Data merek harus berupa array",
  "Brand must be an integer" = "Data merek harus berupa angka",
  "Type is required" = "Tipe tidak boleh kosong",
  "Type must be an array" = "Data tipe harus berupa array",
  "Type must be an integer" = "Data tipe harus berupa angka",

  "Invalid group report" = "Grup laporan harus merupakan merek atau tipe produk.",
  "Sort by required" = "Urutan dibutuhkan",
  "Sort direction only supports ascending or descending" = "Urutan hanya dapat dilakukan secara ascending atau descending",
  "Amount is required" = "Nominal tidak boleh kosong",
  "Amount must be numeric" = "Nominal harus berupa angka",
  "Sales invoice payment is greater than value" = "Nilai pembayaran lebih besar daripada nilai nota",
  "Deposit already confirmed" = "Deposit sudah dikonfirmasi atau dihapus sebelumnya",

  "Page is required" = "Halaman tidak boleh kosong",
  "Page must be numeric" = "Parameter halaman harus berupa angka",
  "Page size is required" = "Jumlah data tidak boleh kosong",
  "Page size must be numeric" = "Parameter jumlah data harus berupa angka",
  "Sales deposit payment is greater than value" = "Nominal pembayaran lebih besar daripada nilai bon",
  "Payment is required" = "Data pembayaran tidak boleh kosong",
  "Payment must be an array" = "Data pembayaran harus berupa array",
  "Payment date is required" = "Data tanggal pembayaran tidak boleh kosong",
  "Promotion not found" = "Promosi tidak ditemukan",
  "Supplier has been used" = "Data supplier sudah digunakan sebelumnya sehingga tidak dihapus. Mohon periksa kembali.",
  "Sales invoice not found" = "Data faktur penjualan tidak ditemukan",
}

export default ErrorList;
