enum ErrorList {
  "Auth error" = "Terjadi kesalahan pada saat melakukan autentikasi. Mohon periksa kembali informasi login anda.",
  "Not found" = "Data tidak ditemukan.",
  "Unknown error" = "Terjadi kesalahan yang tidak diketahui. Mohon hubungi administrator.",
  "Parameter error" = "Terjadi kesalahan pada parameter yang diberikan. Mohon periksa kembali.",
  "Delete error" = "Terjadi kesalahan pada saat menghapus data. Mohon hubungi administrator.",
  "Duplicate error" = "Data yang anda masukkan sudah ada sebelumnya. Mohon periksa kembali.",
  "ID is required" = "ID tidak boleh kosong.",
  "Address required" = "Alamat tidak boleh kosong.",
  "User not active" = "Pengguna tidak aktif.",
  "User not found" = "Pengguna tidak ditemukan.",
  "User already exist" = "Pengguna sudah ada sebelumnya.",
  "Role not found" = "Peran tidak ditemukan.",
  "UUID required" = "UUID tidak boleh kosong.",
  "Package item id required" = "ID item paket tidak boleh kosong.",
  "Package item quantity required" = "Kuantitas item paket tidak boleh kosong.",

  "Product not found" = "Data produk tidak ditemukan.",
  "Product unit not found" = "Data satuan produk tidak ditemukan.",
  "Product package not found" = "Data paket produk tidak ditemukan.",
  "Price is required" = "Harga tidak boleh kosong.",
  "Package name required" = "Nama paket tidak boleh kosong.",
  "Package description required" = "Deskripsi paket tidak boleh kosong.",
  "Package items required" = "Item paket tidak boleh kosong.",
  "Brand unique constraint" = "Nama merek sudah ada sebelumnya.",
  "Reference unique constraint" = "Referensi sudah ada sebelumnya.",

  "Unable to delete" = "Tidak dapat menghapus data.",
  "Invoice already confirmed" = "Invoice sudah dikonfirmasi.",
  "Invoice already deleted" = "Invoice sudah dihapus.",
  "Invoice not found" = "Data invoice tidak ditemukan.",
  "Purchase invoice not found" = "Data invoice pembelian tidak ditemukan.",
  "Purchase invoice already confirmed" = "Invoice pembelian sudah dikonfirmasi.",
  "Purchase invoice already deleted" = "Invoice pembelian sudah dihapus.",
  "Payment method required" = "Metode pembayaran tidak boleh kosong.",
  "Delivery required" = "Pengiriman tidak boleh kosong.",
  "Service required" = "Biaya layanan tidak boleh kosong.",

  "Good receipt not found" = "Data penerimaan barang tidak ditemukan.",
  "Good receipt already confirmed" = "Penerimaan barang sudah dikonfirmasi.",
  "Good receipt already deleted" = "Penerimaan barang sudah dihapus.",
  "Date required" = "Tanggal tidak boleh kosong.",
  "Name required" = "Nama tidak boleh kosong.",
  "Supplier ID required" = "ID supplier tidak boleh kosong.",
  "Company ID required" = "ID perusahaan tidak boleh kosong.",
  "Discount required" = "Diskon tidak boleh kosong.",
  "Purchase invoice name required" = "Nama invoice pembelian tidak boleh kosong.",
  "Adjustment case not found" = "Data kasus penyesuaian tidak ditemukan.",
  "Delete bill sales return constraint" = "Tidak dapat menghapus faktur karena ada retur penjualan yang terkait.",

  "Expense type not found" = "Data jenis pengeluaran tidak ditemukan.",
  "Expense type has child" = "Jenis pengeluaran memiliki sub jenis.",

  "No changes" = "Tidak ada perubahan.",

  "Password required" = "Password tidak boleh kosong.",
  "User role required" = "Role pengguna tidak boleh kosong.",
  "Username is required" = "Username tidak boleh kosong.",

  "Item is required" = "Item tidak boleh kosong.",
  "Internal server error" = "Terjadi kesalahan pada server. Mohon hubungi administrator.",
}

export default ErrorList;
